package Vista;

import Logica.ControlGeneral;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.time.Instant;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Estudiantes
 */
public class FormularioPrestamo extends javax.swing.JFrame {

    private ControlGeneral cg;
    private List jtextos;
    private MenuCajero mc;
    private LocalDate fechaAutorizacion;

    /**
     * Creates new form FormularioPrestamo
     *
     * @param mc
     * @param cg
     */
    public FormularioPrestamo(MenuCajero mc, ControlGeneral cg) {
        this.mc = mc;
        this.cg = cg;
        initComponents();
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ingresoNumeroPrestamos = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ingresoNumeroPrestamos1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        ingresoNumeroPrestamos2 = new javax.swing.JTextField();
        ingresoNumeroPrestamos2.addKeyListener(new KeyAdapter() {
            @Override
            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();
                if (Character.isDigit(c)) {
                    e.consume(); // evita que el número se escriba
                }
            }
        });
        jLabel6 = new javax.swing.JLabel();
        ingresoNumeroPrestamos3 = new javax.swing.JTextField();
        ingresoNumeroPrestamos3.addKeyListener(new KeyAdapter() {
            @Override
            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();
                if (Character.isDigit(c)) {
                    e.consume(); // evita que el número se escriba
                }
            }
        });
        jLabel7 = new javax.swing.JLabel();
        ingresoNumeroPrestamos4 = new javax.swing.JTextField();
        ingresoNumeroPrestamos4.addKeyListener(new KeyAdapter() {
            @Override
            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();
                if (Character.isDigit(c)) {
                    e.consume(); // evita que el número se escriba
                }
            }
        });
        jLabel8 = new javax.swing.JLabel();
        ingresoNumeroPrestamos5 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        ingresoNumeroPrestamos6 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        ingresoNumeroPrestamos7 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser1.addKeyListener(new KeyAdapter() {
            @Override
            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();
                if (Character.isDigit(c)||Character.isAlphabetic(c)) {
                    e.consume(); // evita que el número se escriba
                }
            }
        });
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(java.awt.SystemColor.inactiveCaption);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Datos del Solicitante");

        jLabel2.setBackground(new java.awt.Color(204, 255, 204));
        jLabel2.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Solicitud de prestamos");
        jLabel2.setToolTipText("");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel2.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        ingresoNumeroPrestamos.setToolTipText("");
        ingresoNumeroPrestamos.setMinimumSize(new java.awt.Dimension(120, 22));
        ingresoNumeroPrestamos.setPreferredSize(new java.awt.Dimension(120, 22));
        ingresoNumeroPrestamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresoNumeroPrestamosActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Numero de prestamo:");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Numero Identificacion:");

        ingresoNumeroPrestamos1.setToolTipText("");
        ingresoNumeroPrestamos1.setMinimumSize(new java.awt.Dimension(120, 22));
        ingresoNumeroPrestamos1.setPreferredSize(new java.awt.Dimension(120, 22));
        ingresoNumeroPrestamos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresoNumeroPrestamos1ActionPerformed(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Primer Nombre:");

        ingresoNumeroPrestamos2.setToolTipText("");
        ingresoNumeroPrestamos2.setMinimumSize(new java.awt.Dimension(120, 22));
        ingresoNumeroPrestamos2.setPreferredSize(new java.awt.Dimension(120, 22));
        ingresoNumeroPrestamos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresoNumeroPrestamos2ActionPerformed(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Primer Apellido:");

        ingresoNumeroPrestamos3.setToolTipText("");
        ingresoNumeroPrestamos3.setMinimumSize(new java.awt.Dimension(120, 22));
        ingresoNumeroPrestamos3.setPreferredSize(new java.awt.Dimension(120, 22));
        ingresoNumeroPrestamos3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresoNumeroPrestamos3ActionPerformed(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Segundo Apellido:");

        ingresoNumeroPrestamos4.setToolTipText("");
        ingresoNumeroPrestamos4.setMinimumSize(new java.awt.Dimension(120, 22));
        ingresoNumeroPrestamos4.setPreferredSize(new java.awt.Dimension(120, 22));
        ingresoNumeroPrestamos4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresoNumeroPrestamos4ActionPerformed(evt);
            }
        });

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Numero de Telefono:");

        ingresoNumeroPrestamos5.setToolTipText("");
        ingresoNumeroPrestamos5.setMinimumSize(new java.awt.Dimension(120, 22));
        ingresoNumeroPrestamos5.setPreferredSize(new java.awt.Dimension(120, 22));
        ingresoNumeroPrestamos5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresoNumeroPrestamos5ActionPerformed(evt);
            }
        });

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Numero de Celular:");

        ingresoNumeroPrestamos6.setToolTipText("");
        ingresoNumeroPrestamos6.setMinimumSize(new java.awt.Dimension(120, 22));
        ingresoNumeroPrestamos6.setPreferredSize(new java.awt.Dimension(120, 22));
        ingresoNumeroPrestamos6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresoNumeroPrestamos6ActionPerformed(evt);
            }
        });

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Datos del Prestamo");

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Valor del prestamo:");

        ingresoNumeroPrestamos7.setToolTipText("");
        ingresoNumeroPrestamos7.setMinimumSize(new java.awt.Dimension(120, 22));
        ingresoNumeroPrestamos7.setPreferredSize(new java.awt.Dimension(120, 22));
        ingresoNumeroPrestamos7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresoNumeroPrestamos7ActionPerformed(evt);
            }
        });

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Fecha de autorizacion:");

        jDateChooser1.setToolTipText("01/12/2000");
        jDateChooser1.setDateFormatString("dd-MM-yyyy");
        jDateChooser1.setFocusCycleRoot(true);
        jDateChooser1.setInheritsPopupMenu(true);
        jDateChooser1.setMinSelectableDate(new java.util.Date(-62135747911000L));

        jButton5.setBackground(java.awt.SystemColor.activeCaption);
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("SALIR");
        jButton5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 51, 255), null));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(java.awt.SystemColor.activeCaption);
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("ENVIAR");
        jButton6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 51, 255), null));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setBackground(java.awt.SystemColor.activeCaption);
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("ATRAS");
        jButton7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 51, 255), null));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(244, 244, 244)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ingresoNumeroPrestamos3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ingresoNumeroPrestamos4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ingresoNumeroPrestamos5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ingresoNumeroPrestamos6, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(ingresoNumeroPrestamos1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(ingresoNumeroPrestamos2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(107, 107, 107)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(ingresoNumeroPrestamos, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(ingresoNumeroPrestamos7, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(297, 297, 297)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 22, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ingresoNumeroPrestamos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ingresoNumeroPrestamos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ingresoNumeroPrestamos2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ingresoNumeroPrestamos7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ingresoNumeroPrestamos3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ingresoNumeroPrestamos4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ingresoNumeroPrestamos5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ingresoNumeroPrestamos6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ingresoNumeroPrestamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresoNumeroPrestamosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingresoNumeroPrestamosActionPerformed

    private void ingresoNumeroPrestamos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresoNumeroPrestamos1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingresoNumeroPrestamos1ActionPerformed

    private void ingresoNumeroPrestamos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresoNumeroPrestamos2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingresoNumeroPrestamos2ActionPerformed

    private void ingresoNumeroPrestamos3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresoNumeroPrestamos3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingresoNumeroPrestamos3ActionPerformed

    private void ingresoNumeroPrestamos4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresoNumeroPrestamos4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingresoNumeroPrestamos4ActionPerformed

    private void ingresoNumeroPrestamos5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresoNumeroPrestamos5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingresoNumeroPrestamos5ActionPerformed

    private void ingresoNumeroPrestamos6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresoNumeroPrestamos6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingresoNumeroPrestamos6ActionPerformed

    private void ingresoNumeroPrestamos7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresoNumeroPrestamos7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingresoNumeroPrestamos7ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

        listarCamposTextos();
        if (validarCamposVacios()) {
            if (validarCamposNumericos()) {
                fechaAutorizacion = Instant.ofEpochMilli(jDateChooser1.getDate().getTime()).atZone(ZoneId.systemDefault()).toLocalDate();
                if (fechaAutorizacion.getDayOfMonth() <= 20) {
                    cg.enviarSolicitanteBanco(ingresoNumeroPrestamos5.getText(), ingresoNumeroPrestamos6.getText(), ingresoNumeroPrestamos1.getText(), ingresoNumeroPrestamos2.getText(), ingresoNumeroPrestamos3.getText(), ingresoNumeroPrestamos4.getText());
                    cg.enviarPrestamoBanco(ingresoNumeroPrestamos7.getText(), ingresoNumeroPrestamos.getText(), fechaAutorizacion);
                } else {
                    JOptionPane.showMessageDialog(null, "Los préstamos solo se pueden autorizar en los primeros 20 días del mes.", "!Fecha de autorizacion erronea¡", 1);
                    //return;
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Ingrese la informacion completa y correcta del prestamo", "!Informacion incompleta¡", 1);
        }

    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        mc.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    public void listarCamposTextos() {
        jtextos = new ArrayList();
        jtextos.add(ingresoNumeroPrestamos.getText());
        jtextos.add(ingresoNumeroPrestamos1.getText());
        jtextos.add(ingresoNumeroPrestamos2.getText());
        jtextos.add(ingresoNumeroPrestamos3.getText());
        jtextos.add(ingresoNumeroPrestamos4.getText());
        jtextos.add(ingresoNumeroPrestamos5.getText());
        jtextos.add(ingresoNumeroPrestamos6.getText());
        jtextos.add(ingresoNumeroPrestamos7.getText());
        jtextos.add(jDateChooser1.getDate());
    }

    public boolean validarCamposNumericos() {
        try {
            Integer.valueOf(ingresoNumeroPrestamos1.getText());//n identificacion
            Integer.valueOf(ingresoNumeroPrestamos5.getText());//telefono
            Integer.valueOf(ingresoNumeroPrestamos6.getText());//celular
            Integer.valueOf(ingresoNumeroPrestamos.getText());//n prestamo
            Double.valueOf(ingresoNumeroPrestamos7.getText());//valor prestamo
//            if (ingresoNumeroPrestamos1.getText().length() <= 6 || ingresoNumeroPrestamos1.getText().length() > 10) {
//                cg.mostrarJOption("El numero de identificacion no existe");
//                return false;
//            }
//            if (ingresoNumeroPrestamos5.getText().length() != 10) {
//                cg.mostrarJOption("El numero de telefono fijo no existe");
//                return false;
//            }
//            if (ingresoNumeroPrestamos6.getText().length() != 10) {
//                cg.mostrarJOption("El numero de telefono movil no existe");
//                return false;
//            }
            if (ingresoNumeroPrestamos.getText().length() > 10 || ingresoNumeroPrestamos.getText().length() < 0) {
                cg.mostrarJOption("El numero del prestamo es incorrecto");
                return false;
            }
        } catch (Exception e) {
            cg.mostrarJOption("Valores numericos incorrectos y/o con formato incompatible");
            return false;
        }
        return true;
    }

    public boolean validarCamposVacios() {
        for (int i = 0; i < jtextos.size(); i++) {
            if (jtextos.get(i) == null || jtextos.get(i).toString() == null || jtextos.get(i).toString().trim().isEmpty()) {
                return false;
            }
        }
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ingresoNumeroPrestamos;
    private javax.swing.JTextField ingresoNumeroPrestamos1;
    private javax.swing.JTextField ingresoNumeroPrestamos2;
    private javax.swing.JTextField ingresoNumeroPrestamos3;
    private javax.swing.JTextField ingresoNumeroPrestamos4;
    private javax.swing.JTextField ingresoNumeroPrestamos5;
    private javax.swing.JTextField ingresoNumeroPrestamos6;
    private javax.swing.JTextField ingresoNumeroPrestamos7;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
